"""Dashboard scaffold — generates a clean, data-wired, editable HTML template.

Different from `workflowx dashboard` (static snapshot) and `workflowx serve`
(live server shell). The scaffold is designed to be EDITED — by you, or by
Claude via MCP — so it prioritises:

  1. All WorkflowX data embedded as a JS object (WX_DATA) — Claude can see
     exactly what's available and reference it by name.
  2. Each chart in its own clearly-commented section — targeted edits don't
     touch unrelated code.
  3. Zero build step — pure HTML/CSS/JS with Chart.js from CDN.
  4. Live-reload ready — open via `workflowx serve --file <output> --watch`
     and the browser auto-reloads on every save.

Typical workflow:
    workflowx scaffold --output my-dashboard.html
    workflowx serve --file my-dashboard.html --watch
    # Ask Claude to edit my-dashboard.html — browser updates on each save
"""

from __future__ import annotations

import json
from datetime import date, timedelta
from typing import Any


def _load_data(config: Any, store: Any) -> dict[str, Any]:
    """Pull current WorkflowX data and return as scaffold-ready dict."""
    from workflowx.inference.patterns import compute_friction_trends, detect_patterns
    from workflowx.measurement import compute_roi_summary

    today = date.today()
    all_sessions = []
    for i in range(30):
        d = today - timedelta(days=i)
        all_sessions.extend(store.load_sessions(d))

    patterns = detect_patterns(all_sessions) if all_sessions else []
    trends = compute_friction_trends(all_sessions) if all_sessions else []
    outcomes = store.load_outcomes()
    roi = compute_roi_summary(outcomes)

    return {
        "generated_on": today.isoformat(),
        "sessions": [
            {
                "date": s.start_time.strftime("%Y-%m-%d"),
                "time": f"{s.start_time.strftime('%H:%M')}-{s.end_time.strftime('%H:%M')}",
                "duration_min": round(s.total_duration_minutes, 1),
                "apps": s.apps_used[:5],
                "switches": s.context_switches,
                "friction": s.friction_level.value,
                "intent": s.inferred_intent or "",
            }
            for s in sorted(all_sessions, key=lambda s: s.start_time, reverse=True)[:50]
        ],
        "patterns": [
            {
                "intent": p.intent,
                "occurrences": p.occurrences,
                "avg_duration_min": round(p.avg_duration_minutes, 1),
                "total_time_min": round(p.total_time_invested_minutes, 1),
                "friction": p.most_common_friction.value,
                "trend": p.trend,
                "apps": p.apps_involved[:5],
            }
            for p in patterns[:10]
        ],
        "trends": [
            {
                "week": t.week_label,
                "total_min": round(t.total_minutes, 1),
                "friction_ratio": round(t.high_friction_ratio, 3),
                "avg_switches": round(t.avg_switches_per_session, 1),
            }
            for t in trends
        ],
        "outcomes": [
            {
                "intent": o["intent"],
                "before_min": o["before"],
                "after_min": o["after"],
                "savings_min": o["savings"],
                "status": o.get("status", "measuring"),
            }
            for o in roi["outcomes"]
        ],
        "kpis": {
            "weekly_savings_min": roi["total_weekly_savings_minutes"],
            "weekly_savings_hrs": roi["total_weekly_savings_hours"],
            "cumulative_savings_hrs": roi["total_cumulative_savings_hours"],
            "total_outcomes": roi["total_outcomes"],
            "adopted": roi["adopted"],
            "rejected": roi["rejected"],
            "measuring": roi["measuring"],
            "adoption_rate": roi["adoption_rate"],
        },
    }


def generate_scaffold_html(config: Any, store: Any, hourly_rate: float = 75.0) -> str:
    """Generate a complete, data-wired, editable HTML dashboard.

    All data is embedded as WX_DATA — a plain JS object. Charts are in
    clearly-labelled sections. Add, remove, or modify sections freely;
    reference WX_DATA.sessions, WX_DATA.patterns, WX_DATA.kpis, etc.
    """
    data = _load_data(config, store)
    wx_data_json = json.dumps(data, indent=2)
    hourly_rate_js = json.dumps(hourly_rate)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>WorkflowX Dashboard</title>
<!--
  Generated by: workflowx scaffold
  Data as of:   {data['generated_on']}
  Hourly rate:  ${hourly_rate}/hr

  EDITING THIS FILE:
  - All data lives in WX_DATA (see <script id="wx-data"> below)
  - Each chart section is labelled — edit independently
  - Regenerate data: workflowx scaffold --output <this file>
  - Live preview:    workflowx serve --file <this file> --watch
-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js"></script>
<style>
  /* ── Reset + base ── */
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background: #0d1117;
    color: #c9d1d9;
    padding: 24px;
    max-width: 1400px;
    margin: 0 auto;
  }}

  /* ── Typography ── */
  h1 {{ color: #f0f6fc; font-size: 28px; margin-bottom: 4px; }}
  h2 {{ color: #f0f6fc; font-size: 18px; font-weight: 600; margin-bottom: 16px; }}
  .subtitle {{ color: #8b949e; font-size: 14px; margin-bottom: 32px; }}

  /* ── KPI cards ── */
  .kpi-grid {{
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 16px;
    margin-bottom: 32px;
  }}
  .kpi-card {{
    background: #161b22;
    border: 1px solid #30363d;
    border-radius: 8px;
    padding: 20px;
  }}
  .kpi-label {{ color: #8b949e; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; }}
  .kpi-value {{ color: #f0f6fc; font-size: 30px; font-weight: 700; margin-top: 6px; }}
  .kpi-value.positive {{ color: #3fb950; }}
  .kpi-sub {{ color: #8b949e; font-size: 12px; margin-top: 4px; }}

  /* ── Chart panels ── */
  .section {{ margin-bottom: 32px; }}
  .chart-panel {{
    background: #161b22;
    border: 1px solid #30363d;
    border-radius: 8px;
    padding: 24px;
    margin-bottom: 16px;
  }}
  .two-col {{
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 16px;
  }}
  @media (max-width: 900px) {{ .two-col {{ grid-template-columns: 1fr; }} }}

  /* ── Sessions table ── */
  table {{
    width: 100%;
    border-collapse: collapse;
    font-size: 13px;
  }}
  th {{
    text-align: left;
    color: #8b949e;
    font-weight: 500;
    padding: 8px 12px;
    border-bottom: 1px solid #30363d;
  }}
  td {{
    padding: 8px 12px;
    border-bottom: 1px solid #21262d;
    vertical-align: top;
  }}
  tr:last-child td {{ border-bottom: none; }}
  .badge {{
    display: inline-block;
    padding: 2px 8px;
    border-radius: 12px;
    font-size: 11px;
    font-weight: 500;
  }}
  .badge-critical {{ background: rgba(248,81,73,0.15); color: #f85149; }}
  .badge-high     {{ background: rgba(210,153,34,0.15); color: #d29922; }}
  .badge-medium   {{ background: rgba(88,166,255,0.15); color: #58a6ff; }}
  .badge-low      {{ background: rgba(63,185,80,0.15); color: #3fb950; }}

  /* ── Footer ── */
  .footer {{ text-align: center; color: #484f58; font-size: 12px; margin-top: 40px; }}
  .footer a {{ color: #58a6ff; text-decoration: none; }}
</style>
</head>
<body>

<!-- ══════════════════════════════════════════════════════════════════════════
     DATA — embedded from WorkflowX storage
     Reference as: WX_DATA.kpis, WX_DATA.sessions, WX_DATA.patterns, etc.
     Regenerate: workflowx scaffold --output <this file>
     ══════════════════════════════════════════════════════════════════════════ -->
<script id="wx-data" type="application/json">
{wx_data_json}
</script>
<script>
const WX_DATA = JSON.parse(document.getElementById('wx-data').textContent);
const HOURLY_RATE = {hourly_rate_js};
</script>

<!-- ══════════════════════════════════════════════════════════════════════════
     HEADER
     ══════════════════════════════════════════════════════════════════════════ -->
<h1>WorkflowX Dashboard</h1>
<p class="subtitle" id="subtitle">Loading...</p>

<!-- ══════════════════════════════════════════════════════════════════════════
     KPI CARDS — edit labels/values below, or add/remove cards freely
     ══════════════════════════════════════════════════════════════════════════ -->
<div class="kpi-grid" id="kpi-grid">
  <!-- Populated by renderKPIs() -->
</div>

<!-- ══════════════════════════════════════════════════════════════════════════
     SECTION 1: Friction Trends + Top Patterns (side by side)
     ══════════════════════════════════════════════════════════════════════════ -->
<div class="section">
  <div class="two-col">
    <div class="chart-panel">
      <h2>Friction Over Time</h2>
      <canvas id="chart-friction"></canvas>
    </div>
    <div class="chart-panel">
      <h2>Top Patterns by Time (min)</h2>
      <canvas id="chart-patterns"></canvas>
    </div>
  </div>
</div>

<!-- ══════════════════════════════════════════════════════════════════════════
     SECTION 2: ROI Before vs After
     ══════════════════════════════════════════════════════════════════════════ -->
<div class="section">
  <div class="chart-panel">
    <h2>Replacement ROI — Before vs After (min/week)</h2>
    <canvas id="chart-roi"></canvas>
  </div>
</div>

<!-- ══════════════════════════════════════════════════════════════════════════
     SECTION 3: Recent Sessions Table
     ══════════════════════════════════════════════════════════════════════════ -->
<div class="section">
  <div class="chart-panel">
    <h2>Recent Sessions</h2>
    <table id="sessions-table">
      <thead>
        <tr>
          <th>Time</th><th>Duration</th><th>Apps</th><th>Switches</th>
          <th>Friction</th><th>Intent</th>
        </tr>
      </thead>
      <tbody id="sessions-tbody"><!-- Populated by renderSessions() --></tbody>
    </table>
  </div>
</div>

<div class="footer">
  <a href="https://github.com/wjlgatech/workflowx">WorkflowX</a> &mdash;
  data as of {data['generated_on']} &mdash;
  regenerate with <code>workflowx scaffold</code>
</div>

<!-- ══════════════════════════════════════════════════════════════════════════
     RENDERING — all functions reference WX_DATA
     ══════════════════════════════════════════════════════════════════════════ -->
<script>
Chart.defaults.color = '#8b949e';
Chart.defaults.borderColor = '#30363d';

// ── Header ──────────────────────────────────────────────────────────────────
document.getElementById('subtitle').textContent =
  'Data as of ' + WX_DATA.generated_on + ' · ' +
  WX_DATA.sessions.length + ' sessions · ' +
  WX_DATA.patterns.length + ' patterns detected';

// ── KPI Cards ───────────────────────────────────────────────────────────────
function renderKPIs() {{
  const k = WX_DATA.kpis;
  const weeklySavingsUsd = (k.weekly_savings_hrs * HOURLY_RATE).toFixed(0);
  const cumulUsd = (k.cumulative_savings_hrs * HOURLY_RATE).toFixed(0);

  const cards = [
    {{
      label: 'Weekly Time Saved',
      value: Math.round(k.weekly_savings_min) + ' min',
      sub: k.weekly_savings_hrs.toFixed(1) + ' hrs · $' + weeklySavingsUsd + '/wk',
      positive: true,
    }},
    {{
      label: 'Cumulative Savings',
      value: k.cumulative_savings_hrs.toFixed(1) + ' hrs',
      sub: '$' + cumulUsd + ' total value',
      positive: true,
    }},
    {{
      label: 'Replacements',
      value: k.total_outcomes,
      sub: k.adopted + ' adopted · ' + k.rejected + ' rejected · ' + k.measuring + ' measuring',
      positive: false,
    }},
    {{
      label: 'Adoption Rate',
      value: Math.round(k.adoption_rate * 100) + '%',
      sub: 'of proposed replacements working',
      positive: false,
    }},
  ];

  const grid = document.getElementById('kpi-grid');
  grid.innerHTML = cards.map(c => `
    <div class="kpi-card">
      <div class="kpi-label">${{c.label}}</div>
      <div class="kpi-value ${{c.positive ? 'positive' : ''}}">${{c.value}}</div>
      <div class="kpi-sub">${{c.sub}}</div>
    </div>
  `).join('');
}}

// ── Chart 1: Friction trend line ─────────────────────────────────────────────
function renderFrictionChart() {{
  new Chart(document.getElementById('chart-friction'), {{
    type: 'line',
    data: {{
      labels: WX_DATA.trends.map(t => t.week),
      datasets: [{{
        label: 'High Friction %',
        data: WX_DATA.trends.map(t => +(t.friction_ratio * 100).toFixed(1)),
        borderColor: '#f85149',
        backgroundColor: 'rgba(248,81,73,0.1)',
        fill: true,
        tension: 0.3,
      }}]
    }},
    options: {{
      responsive: true,
      plugins: {{ legend: {{ display: false }} }},
      scales: {{ y: {{ beginAtZero: true, max: 100, ticks: {{ callback: v => v + '%' }} }} }}
    }}
  }});
}}

// ── Chart 2: Top patterns bar ─────────────────────────────────────────────────
function renderPatternsChart() {{
  const top = WX_DATA.patterns.slice(0, 8);
  new Chart(document.getElementById('chart-patterns'), {{
    type: 'bar',
    data: {{
      labels: top.map(p => p.intent.slice(0, 28)),
      datasets: [{{
        label: 'Total minutes',
        data: top.map(p => Math.round(p.total_time_min)),
        backgroundColor: '#58a6ff',
        borderRadius: 4,
      }}]
    }},
    options: {{
      responsive: true,
      indexAxis: 'y',
      plugins: {{ legend: {{ display: false }} }},
    }}
  }});
}}

// ── Chart 3: ROI before/after ─────────────────────────────────────────────────
function renderROIChart() {{
  const outcomes = WX_DATA.outcomes.slice(0, 10);
  if (!outcomes.length) return;
  new Chart(document.getElementById('chart-roi'), {{
    type: 'bar',
    data: {{
      labels: outcomes.map(o => o.intent.slice(0, 22)),
      datasets: [
        {{
          label: 'Before (min/wk)',
          data: outcomes.map(o => o.before_min),
          backgroundColor: '#f85149',
          borderRadius: 4,
        }},
        {{
          label: 'After (min/wk)',
          data: outcomes.map(o => o.after_min),
          backgroundColor: '#3fb950',
          borderRadius: 4,
        }},
      ]
    }},
    options: {{
      responsive: true,
      plugins: {{ legend: {{ position: 'top' }} }},
    }}
  }});
}}

// ── Table: Recent sessions ────────────────────────────────────────────────────
function renderSessions() {{
  const badgeClass = {{
    critical: 'badge-critical', high: 'badge-high',
    medium: 'badge-medium', low: 'badge-low',
  }};
  const rows = WX_DATA.sessions.slice(0, 20).map(s => `
    <tr>
      <td>${{s.date}} ${{s.time}}</td>
      <td>${{s.duration_min}} min</td>
      <td style="color:#8b949e">${{s.apps.join(', ') || '—'}}</td>
      <td>${{s.switches}}</td>
      <td><span class="badge ${{badgeClass[s.friction] || ''}}">${{s.friction}}</span></td>
      <td style="color:#8b949e;max-width:320px">${{s.intent || '—'}}</td>
    </tr>
  `).join('');
  document.getElementById('sessions-tbody').innerHTML = rows || '<tr><td colspan="6" style="color:#484f58">No sessions yet</td></tr>';
}}

// ── Init ──────────────────────────────────────────────────────────────────────
renderKPIs();
renderFrictionChart();
renderPatternsChart();
renderROIChart();
renderSessions();
</script>
</body>
</html>"""
